#!/bin/bash
if [ $# -ne 1 ]
then
	echo "Úsáid: opp-c clar.opp"
	echo "Má thugtar - mar clar.opp, léann sé an clár ó STDIN"
	exit 1 
fi
TMPFILE='./sealadach.c'
cat "${1}" | perl clean.pl | sed -f opp2c.sed > $TMPFILE
gcc -o ./a.out $TMPFILE
./a.out
rm -f ${TMPFILE} ./a.out
